// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5IuD6EL_Ixr1QqJEagpjoJCg5oWXm2xM',
    appId: '1:932517148487:web:e7de0a9dde685b13813e62',
    messagingSenderId: '932517148487',
    projectId: 'geo-exam-36ca2',
    authDomain: 'geo-exam-36ca2.firebaseapp.com',
    databaseURL: 'https://geo-exam-36ca2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geo-exam-36ca2.appspot.com',
    measurementId: 'G-N0RSR96TT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPk_oYQ7IsOXnmFRBfHsj-dXAEQ6FCWu8',
    appId: '1:932517148487:android:4bb76c43f6c714f7813e62',
    messagingSenderId: '932517148487',
    projectId: 'geo-exam-36ca2',
    databaseURL: 'https://geo-exam-36ca2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geo-exam-36ca2.appspot.com',
  );
}
